### ISSUE TITLE
.tab-active { border-left-color: blue; border-left-width: 2px; }

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/hyperterm-one-light#2]
Before
![screen shot 2016-07-21 at 01 52 06](https://cloud.githubusercontent.com/assets/559321/17007057/e559e94c-4ee5-11e6-8ea3-2026d6aeb6c4.png)

After
![screen shot 2016-07-21 at 01 59 27](https://cloud.githubusercontent.com/assets/559321/17007177/c9f53d9a-4ee6-11e6-9e82-8ee333849e81.png)

Code will be smth like this, will submit pull-request if change sounds reasonable

```css
li.tab_tab::before {
    content: "";
    position: absolute;
    pointer-events: none;
    z-index: 2;
    top: 0px;
    left: 0px;
    bottom: -1px;
    width: 2px;
    border-top-left-radius: inherit;
    border-radius: 3px 0;
    background: #475fd7;
    opacity: 0;
    transition: opacity .16s;
}

li.tab_tab.tab_active::before {
    opacity: 1;
    transition-duration: .32s;
}
```
